### ISSUE TITLE
Traceback when deployed on server

### ISSUE THREAD

**Issue by ashwini0529** [GDGVIT/Hack-Notifier-API#2]
http://paste.ubuntu.com/24234066/

**Comment by samyak-jain** [comment]
I believe html5lib needs to be installed on the server.

**Comment by ashwini0529** [comment]
```
    HTTPServerRequest(protocol='http', host='blog.gdgvitvellore.com:8000', method='GET', uri='/', version='HTTP/1.1', remote_ip='163.47.15.24', headers={'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': 'blog.gdgvitvellore.com:8000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': 'wp-settings-2=libraryContent%3Dbrowse%26editor%3Dtinymce; wp-settings-time-2=1487673296; pvc_visits[0]=1490358793b86a1490358803b31; _ga=GA1.2.26802064.1485451878', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/home/gdgmaster/.local/lib/python2.7/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "serv.py", line 29, in get
        self.write({"status_code": 200, "status_message": "ok", "list": hcom.h_com() + hcom.guide_conf() + hcom.vencity()})
      File "/home/gdgmaster/Hack-Notifier-API/hcom.py", line 16, in h_com
        list_of_events[-1]['start_date'] = date.replace('\xa0', ' ')
      File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
        return codecs.utf_8_decode(input, errors, True)
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 0: invalid start byte
```

**Comment by ashwini0529** [comment]
@samyak-jain check for Unicode.

**Comment by samyak-jain** [comment]
I have written the code in python3.6. I believe unicode is handled differently in python 2 and 3.

**Comment by aalind0** [comment]
@samyak-jain Please add reference to the issue before closing!
